artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/furqanx11/Text-Summarization/raw/main/BBCNewsSummary.zip
  local_data_file : artifacts/data_ingestion/BBCNewsSummary.zip
  unzip_dir : artifacts/data_ingestion
  load_data_dir : artifacts/data_ingestion/BBC News Summary

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["dataset.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset.csv
  tokenizer_name: t5-small

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: t5-small

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/BBC
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv